# Generated by Django 2.2.12 on 2021-04-19 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='u_id',
            field=models.UUIDField(default=uuid.UUID('04a49c88-a13f-11eb-b6a3-0242ac130005'), editable=False, primary_key=True, serialize=False),
        ),
    ]
