# Generated by Django 2.2.12 on 2021-04-19 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210420_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='u_id',
            field=models.UUIDField(default=uuid.UUID('f7b8f792-a140-11eb-95c5-0242ac130005'), editable=False, primary_key=True, serialize=False),
        ),
    ]
