# Generated by Django 2.2.12 on 2021-04-19 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210420_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='u_id',
            field=models.UUIDField(default=uuid.UUID('9cb95354-a141-11eb-9ffb-0242ac130005'), editable=False, primary_key=True, serialize=False),
        ),
    ]
