# Generated by Django 2.2.12 on 2021-04-20 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210420_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='u_id',
            field=models.UUIDField(default=uuid.UUID('909dbda0-a194-11eb-acdd-0242ac130005'), editable=False, primary_key=True, serialize=False),
        ),
    ]
