# Generated by Django 2.2.12 on 2021-05-12 11:57

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210423_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=500)),
                ('caption', models.CharField(blank=True, default=None, max_length=5000)),
                ('template_image', models.FileField(blank=True, default=None, null=True, upload_to=core.models.templatespathconvert)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomizeImagefield',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=core.models.imagepathconvert),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to=core.models.imagepathconvert),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=core.models.postspathconvert),
        ),
    ]
