# Generated by Django 2.2.12 on 2021-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210512_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='u_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
