export const UPDATE_POSTS = "UPDATE_POSTS";
export const UPDATE_DRAFTS = "UPDATE_DRAFTS";
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const CLEAR_POST_STATE = "CLEAR_POST_STATE";
// login action types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const LOG_OUT = "LOG_OUT";

// signup
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

export const EDIT_USER_SUCCESSFUL = "EDIT_USER_SUCCESSFUL";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";

export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

// SIGN UP email verification otp
export const SEND_EMAIL_VERIFICATION_OTP_START =
  "SEND_EMAIL_VERIFICATION_OTP_START";
export const SEND_EMAIL_VERIFICATION_OTP_FAILED =
  "SEND_EMAIL_VERIFICATION_OTP_FAILED";
export const SEND_EMAIL_VERIFICATION_OTP_SUCCESSFULLY =
  "SEND_EMAIL_VERIFICATION_OTP_SUCCESSFULLY";
// SIGN UP email verification otp
export const SEND_EMAIL_VERIFICATION_CHECK_OTP_START =
  "SEND_EMAIL_VERIFICATION_CHECK_OTP_START";
export const SEND_EMAIL_VERIFICATION_CHECK_OTP_FAILED =
  "SEND_EMAIL_VERIFICATION_CHECK_OTP_FAILED";
export const SEND_EMAIL_VERIFICATION_CHECK_OTP_SUCCESSFULLY =
  "SEND_EMAIL_VERIFICATION_CHECK_OTP_SUCCESSFULLY";

// forgot password OTP SENT
export const SEND_OTP_START = "SEND_OTP_START";
export const SEND_OTP_FAILED = "SEND_OTP_FAILED";
export const SEND_OTP_SUCCESSFULLY = "SEND_OTP_SUCCESSFULLY";
// forgot password OTP RESENT
export const SEND_OTP_RESEND_START = "SEND_OTP_RESEND_START";
export const SEND_OTP_RESEND_FAILED = "SEND_OTP_RESEND_FAILED";
export const SEND_OTP_RESEND_SUCCESSFULLY = "SEND_OTP_RESEND_SUCCESSFULLY";

// forgot password OTP VERIFY
export const OTP_VERIFY_START = "OTP_VERIFY_START";
export const OTP_VERIFY_FAILED = "OTP_VERIFY_FAILED";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
// forgot password OTP VERIFY
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

// change password
export const PASSWORD_CHANGE_START = "PASSWORD_CHANGE_START";
export const PASSWORD_CHANGE_FAILED = "PASSWORD_CHANGE_FAILED";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";

// update user profile
export const UPDATE_USER_PROFILE_START = "UPDATE_USER_PROFILE_START";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";

// USER TEMPLATES

export const TEMPLATES_UPDATE = "TEMPLATES_UPDATE";
export const TEMPLATE_CREATE_SUCCESS = "TEMPLATE_CREATE_SUCCESS";
export const CLEAR_TEMPLATE_STATE = "CLEAR_TEMPLATE_STATE";

// friends
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_POST_LIKE = "UPDATE_POST_LIKE";

// search
export const FETCH_SEARCH_RESULTS_SUCCESS = "FETCH_SEARCH_RESULTS_SUCCESS";
